const CAMPAIGNS = {
    "0": {
        "id": 0,
        "url": "https://www.gofundme.com/f/A-Dios-Rosita",
        "campaign_id": 17602,
        "auto_fb_post_mode": "TRUE",
        "collected_date": "3/16/2020",
        "category_id": 9,
        "category": "unknown",
        "currencycode": "USD",
        "current_amount": 4943,
        "goal": 8000,
        "donators": 72,
        "days_active": 3247,
        "days_created": 3247,
        "title": "My Rosita\\'s Farewell",
        "description": "Thank you everyone that supported us in funding my mom\\'s funeral. Â WeÂ achievedÂ our goal thanks to family and friends through online and personal donations. Â WeÂ appreciate all the support and every single donation is a blessing.Â              For all those that would like to attend the funeral services they are as follow:                Funeral Service (viewing/rosary) on Thurs @ 6pm-8pm        Whitehurst, 1840 S. CENTER. LOS BANOS, CA. 93635                  Mass/Burial on Fri @ 10amÂ        St. Joseph\\'s Church, 1516 Center Ave., Los Banos, CA             Once again, Thank you.             May God Bless you,              Rosie\\'s ChildrenÂ    -----------------------------------------------------------------------------------------------------------------   I am raising money for my mother\\'s funeral. Â She was always the one taking care of us until the time came in which we needed to take care of her.Â       The money collected will go towards the funeral expenses only.      Supporters can also help by praying for her and wishing her well in her new everlasting life.      Thank you,     Julina Corona  Marco Corona  Sofia Corona  Estefania Corona     P.S. We are PayPal Verified Â    https://www.paypal.com/us/verified/pal=jr-corona @hotmail.com",
        "default_url": "48f1k",
        "has_beneficiary": "FALSE",
        "media_type": 1,
        "project_type": 1,
        "turn_off_donations": 0,
        "user_id": 15019,
        "user_first_name": "Julina",
        "user_last_name": "Corona",
        "user_facebook_id": 1430323937,
        "user_profile_url": "https://graph.facebook.com/v3.0/1430323937/picture",
        "visible_in_search": "TRUE",
        "status": 1,
        "deactivated": "FALSE",
        "state": "active",
        "is_launched": "TRUE",
        "campaign_image_url": "https://2dbdd5116ffa30a49aa8-c03f075f8191fb4e60e74b907071aee8.ssl.cf1.rackcdn.com/17602_1339718440.6702.jpg",
        "created_at": "2011-04-27T22:17:31-05:00",
        "launch_date": "2011-04-26T13:15:21-05:00",
        "campaign_hearts": 69,
        "social_share_total": 61,
        "social_share_last_update": "2017-08-26T19:39:55-05:00",
        "location_city": "Patterson, CA",
        "location_country": "US",
        "location_zip": 95363,
        "is_charity": "FALSE",
        "charity_valid": "FALSE",
        "charity_npo_id": "",
        "charity_name": "",
        "velocity": 0
    },
    "1": {
        "id": 1,
        "url": "https://www.gofundme.com/f/1izexg",
        "campaign_id": 228593,
        "auto_fb_post_mode": "FALSE",
        "collected_date": "3/16/2020",
        "category_id": 0,
        "category": "unknown",
        "currencycode": "USD",
        "current_amount": 1955,
        "goal": 3000,
        "donators": 26,
        "days_active": 2677,
        "days_created": 2677,
        "title": "Volunteering in Africa!",
        "description": "Hi everyone! I have been given this amazing opportunity to go to Africa! I would be working with children in orphanages and in their homes. The organization that I am going through is IVHQ volunteering. The things that I need to pay for is for my airfare, which is where the majority of the money will be going. Also, I need to pay for the trip itself. This will cover all of my meals, airport transportation, my housing, and my 24/7 service with the oraginization. I will be leaving on December 17th for one week. Any amount that you give will be greatly appreciated! Thank you so much!Â",
        "default_url": "1izexg",
        "has_beneficiary": "FALSE",
        "media_type": 1,
        "project_type": 1,
        "turn_off_donations": 0,
        "user_id": 191690,
        "user_first_name": "Jacki",
        "user_last_name": "Corona",
        "user_facebook_id": 1455790794,
        "user_profile_url": "https://graph.facebook.com/v3.0/1455790794/picture",
        "visible_in_search": "TRUE",
        "status": 1,
        "deactivated": "FALSE",
        "state": "active",
        "is_launched": "TRUE",
        "campaign_image_url": "https://2dbdd5116ffa30a49aa8-c03f075f8191fb4e60e74b907071aee8.ssl.cf1.rackcdn.com/228593_1353206581.0749.jpg",
        "created_at": "2012-11-20T13:07:33-06:00",
        "launch_date": "2012-11-16T09:42:39-06:00",
        "campaign_hearts": 22,
        "social_share_total": 7,
        "social_share_last_update": "2017-08-26T04:58:36-05:00",
        "location_city": "Elk Grove Village, IL",
        "location_country": "US",
        "location_zip": 60007,
        "is_charity": "FALSE",
        "charity_valid": "FALSE",
        "charity_npo_id": "",
        "charity_name": "",
        "velocity": 0
    },
    "2": {
        "id": 2,
        "url": "https://www.gofundme.com/f/4hzr5g",
        "campaign_id": 673481,
        "auto_fb_post_mode": "FALSE",
        "collected_date": "3/20/2020",
        "category_id": 3,
        "category": "unknown",
        "currencycode": "USD",
        "current_amount": 1545,
        "goal": 2500,
        "donators": 67,
        "days_active": 2369,
        "days_created": 2369,
        "title": "Please Help Rosie",
        "description": "WARNING GRAPHIC IMAGES   Rosie a beautiful loyal Poodle mix was hit by a car and was dragged 5-7 feet- her family witnessed everything that was happening to Rosie. She suffered serious injuries such as having her right arm ripped open to the bone from underarm to wrist, severe contusions to her neck and back; the impact caused Rosie's ear to be torn off which exposed the cartilage. Her family immediately picked her up and sought help, they took her to a place where they thought would help her; they took her to the Downey Shelter believing that the shelter would help keep Rosie alive. That was the furthest from reality. Luckily, for the family Lisa Corona saw the family and asked if Rosie was sick, once Lisa saw Rosie she knew that Rosie needed help-the shelter was not going to help Rosie but kill her once they convinced the family to surrender her.   Rosie is now at Dr. Werber's office receiving the care she needs to recover from her injuries, she had surgery on Wednesday to re-attach her ear to her skull   she is having surgery again today to do a \"debridement\" on her right leg to completely clean the bone area   scrape off the necrotic skin   tissue from her ligaments. Rosie is going to need long term bandage changes while her right arm is allowed to grow new skin (think of very bad burns on a human)   they will continue the cleaning process to scrape the dead tissue every few days for a few months until she is completely healed.  Please donate any amount you can, funds will be directly given to Dr. Werber for saving Rosie's life.  Thank you for your generosity and love for Rosie and her family.",
        "default_url": "4hzr5g",
        "has_beneficiary": "FALSE",
        "media_type": 1,
        "project_type": 1,
        "turn_off_donations": 0,
        "user_id": 556388,
        "user_first_name": "Lisa",
        "user_last_name": "Michelle Corona",
        "user_facebook_id": 746903751,
        "user_profile_url": "https://graph.facebook.com/v3.0/746903751/picture",
        "visible_in_search": "TRUE",
        "status": 1,
        "deactivated": "FALSE",
        "state": "active",
        "is_launched": "TRUE",
        "campaign_image_url": "https://2dbdd5116ffa30a49aa8-c03f075f8191fb4e60e74b907071aee8.ssl.cf1.rackcdn.com/673481_1381977138.0912.jpg",
        "created_at": "2013-09-24T19:34:38-05:00",
        "launch_date": "2013-09-24T19:34:38-05:00",
        "campaign_hearts": 59,
        "social_share_total": 1113,
        "social_share_last_update": "2017-08-31T09:19:00-05:00",
        "location_city": "",
        "location_country": "",
        "location_zip": 80015,
        "is_charity": "FALSE",
        "charity_valid": "FALSE",
        "charity_npo_id": "",
        "charity_name": "",
        "velocity": 0
    },
    "3": {
        "id": 3,
        "url": "https://www.gofundme.com/f/ErikTorres-SJSTEN",
        "campaign_id": 580495,
        "auto_fb_post_mode": "TRUE",
        "collected_date": "3/16/2020",
        "category_id": 11,
        "category": "unknown",
        "currencycode": "USD",
        "current_amount": 25375,
        "goal": 250000,
        "donators": 219,
        "days_active": 2412,
        "days_created": 2412,
        "title": "Erik Torres _SJS/TEN Liver Transplant",
        "description": "Erik, at 13 yrs. the oldest of 3 children was diagnosed with Steven Johnsons Syndrome/TEN in February 8, 2013 (Originally misdiagnosed on 2/5/13) He had a severe allergic reaction to Azithromycin or Ibuprofen (there is no test to administer to verify which medication it was). He was hospitalized for 1 month - in which he spent 3 weeks in the ICU. Erik was Treated as a burn victim and had several eye procedures done while in the ICU. He lost 70% of his skin. He has currently been diagnosed with the \"vanishing bile duct syndrome\". This is a very rare condition... none of the doctors we have seen have seen this in any patient before. So, he will be placed on the transplant list in hopes of a new liver. Aside from his liver, he developed scars in his eye lids. Which will require more surgeries.  Knowing that there is NO chance of a full recovery our hopes are that we can help him with any current and future medical needs.  So, please if you are able to donate anything - It would mean so much to him/us. If you can't we understand. However, We would ask that you please say a prayer for him and share this page...   THANK YOU so much for taking the time to read this. Thank you for any donations and specially for ALL YOUR PRAYERS!! GOD BLESS YOU ALL!!   *********   Erik, a los 13 aÃ±os. El mayor de 3 hijos se le diagnosticÃ³ sÃ­ndrome de Steven Johnson/TEN en Febrero 8, 2013 (originalmente diagnosticado en 2/5/ 13) habÃ­a una reacciÃ³n alÃ©rgica severa a la azitromicina o ibuprofeno (no existe una prueba para verificar cual fue).  El fue hospitalizado por un perÃ­odo de 1 mes - en el que, durante 3 semanas fueron en la UCI. Erik fue tratado como una vÃ­ctima de quemadura y tuvo varios procedimientos en los ojos durante este tiempo. PerdiÃ³ 70% de su piel. Actualmente ha sido diagnosticado con \"sÃ­ndrome de las vÃ­as biliares\".  Esta es una afecciÃ³n muy rara... ninguno de los mÃ©dicos que hemos consultado han visto esto. Por lo tanto, estarÃ¡ en la lista de trasplante con la esperanza de un nuevo hÃ­gado. \nAparte de su hÃ­gado, Erik, desarrollÃ³ unas cicatrices en sus pÃ¡rpados. Lo que requerirÃ¡ mÃ¡s cirugÃ­as. \nSabiendo que no hay posibilidad de una recuperaciÃ³n completa. Nuestra esperanza es de que lo podamos ayudar con sus actuales y futuras necesidades mÃ©dicas. \n \nPor lo tanto, por favor, si usted es capaz de donar hoy, significarÃ­a mucho para Ã©l. Si no lo comprendemos. Sin embargo, le pedimos que por favor, diga una oraciÃ³n por Ã©l y comparta esta pÃ¡gina... \n \nMUCHAS GRACIAS por tomarse el tiempo de leer esto. Gracias por todas las donaciones y especialmente para TODAS SUS ORACIONES!",
        "default_url": "3vmkrw",
        "has_beneficiary": "FALSE",
        "media_type": 0,
        "project_type": 1,
        "turn_off_donations": 0,
        "user_id": 479264,
        "user_first_name": "Bettie",
        "user_last_name": "Corona",
        "user_facebook_id": 1608343114,
        "user_profile_url": "https://graph.facebook.com/v3.0/1608343114/picture",
        "visible_in_search": "TRUE",
        "status": 1,
        "deactivated": "FALSE",
        "state": "active",
        "is_launched": "TRUE",
        "campaign_image_url": "https://i.ytimg.com/vi/7L52gbI8KMY/0.jpg",
        "created_at": "2013-11-12T00:02:40-06:00",
        "launch_date": "2013-08-08T23:51:03-05:00",
        "campaign_hearts": 188,
        "social_share_total": 3159,
        "social_share_last_update": "2017-08-30T22:31:08-05:00",
        "location_city": "Moreno Valley, CA",
        "location_country": "US",
        "location_zip": 92557,
        "is_charity": "FALSE",
        "charity_valid": "FALSE",
        "charity_npo_id": "",
        "charity_name": "",
        "velocity": 0
    },
    "4": {
        "id": 4,
        "url": "https://www.gofundme.com/f/Reggies-War-On-Lymphoma",
        "campaign_id": 985356,
        "auto_fb_post_mode": "FALSE",
        "collected_date": "3/16/2020",
        "category_id": 11,
        "category": "unknown",
        "currencycode": "USD",
        "current_amount": 4035,
        "goal": 10510,
        "donators": 36,
        "days_active": 2237,
        "days_created": 2237,
        "title": "Reggie's War On Lymphoma",
        "description": "On January 15, 2014, Reggie was diagnosed with Stage 4 Large B-Cell Non-Hodgkin's Lymphoma.   Reggie prefers to call it The Phoma....   He has started his first of 6-8 rounds of aggressive chemotherapy, and unfortunately the bills are starting to pile up.  We were not prepared and are still waiting for his LTD to be processed.  In the meantime, we are expected to pay not only the household bills, but are hit with having to pay his insurance and medical expenses in order to continue treatment.  We have reduced the bills, including giving up my car (loan and insurance costs) but the medical costs are coming in.  The goal above covers his out of pocket expenses so far, insurance costs, and what we anticipate still to come from surgeon and hospital.  We know everyone has their own problems, but if you can help with a few dollars, we would greatly appreciate anything to help this battle, and allow Reggie to focus solely on his recovery, and not the stress of finances.  Reggie is a proud man, and hates to ask for anything from anyone, so I took it upon myself to create this page and ask for help.  We appreciate all the amazing support from everyone, keep those prayers coming.",
        "default_url": "6l0bg0",
        "has_beneficiary": "FALSE",
        "media_type": 1,
        "project_type": 1,
        "turn_off_donations": 0,
        "user_id": 816401,
        "user_first_name": "Bobbi",
        "user_last_name": "Corona Jones",
        "user_facebook_id": 674197074,
        "user_profile_url": "https://graph.facebook.com/v3.0/674197074/picture",
        "visible_in_search": "TRUE",
        "status": 1,
        "deactivated": "FALSE",
        "state": "active",
        "is_launched": "TRUE",
        "campaign_image_url": "https://2dbdd5116ffa30a49aa8-c03f075f8191fb4e60e74b907071aee8.ssl.cf1.rackcdn.com/985356_1391806638.3765.jpg",
        "created_at": "2014-02-09T00:20:12-06:00",
        "launch_date": "2014-01-30T22:07:50-06:00",
        "campaign_hearts": 34,
        "social_share_total": 42,
        "social_share_last_update": "2017-08-30T15:11:00-05:00",
        "location_city": "",
        "location_country": "",
        "location_zip": 76114,
        "is_charity": "FALSE",
        "charity_valid": "FALSE",
        "charity_npo_id": "",
        "charity_name": "",
        "velocity": 0
    }
};
export default CAMPAIGNS;
// console.log(CAMPAIGNS)